In [1]:
import pandas as pd

df = pd.DataFrame({
    "나이": [25,30,28,35],
    "도시": ["서울", "부산", "서울", "대구"],
    "점수": [90, 85, 95, 70],
}, index=["철수", "영희", "민수", "지수"])

print(df)

    나이  도시  점수
철수  25  서울  90
영희  30  부산  85
민수  28  서울  95
지수  35  대구  70

In [3]:
df.loc["영희"]

나이    30
도시    부산
점수    85
Name: 영희, dtype: object

In [4]:
df.loc["영희", "점수"]

np.int64(85)

In [5]:
df.loc["철수": "민수"]

    나이  도시  점수
철수  25  서울  90
영희  30  부산  85
민수  28  서울  95

In [6]:
df.loc[:, "도시"]

철수    서울
영희    부산
민수    서울
지수    대구
Name: 도시, dtype: str

In [7]:
df.loc[["철수", "지수"], ["나이", "점수"]]

    나이  점수
철수  25  90
지수  35  70

In [8]:
df.iloc[0]

나이    25
도시    서울
점수    90
Name: 철수, dtype: object

In [9]:
df.iloc[1, 2]

np.int64(85)

In [10]:
df.iloc[0:2]

    나이  도시  점수
철수  25  서울  90
영희  30  부산  85

In [11]:
df.iloc[:, 0]

철수    25
영희    30
민수    28
지수    35
Name: 나이, dtype: int64

In [12]:
df.iloc[[0,3],[0,2]]

    나이  점수
철수  25  90
지수  35  70

In [13]:
df[df["나이"] >= 30]

    나이  도시  점수
영희  30  부산  85
지수  35  대구  70

In [14]:
df[df["도시"] == "서울"]

    나이  도시  점수
철수  25  서울  90
민수  28  서울  95

In [15]:
df[(df["나이"] >= 28) & (df["점수"] >= 90)]

    나이  도시  점수
민수  28  서울  95

In [16]:
df.loc[df["도시"] == "서울", "점수"]

철수    90
민수    95
Name: 점수, dtype: int64

In [23]:
df.loc['민수', '나이']

np.int64(28)

In [43]:
df.iloc[2, 0].item()

28

In [44]:
df.iloc[-1, -1].item()

70

In [39]:
df[(df['점수'] >= 90)]

    나이  도시  점수
철수  25  서울  90
민수  28  서울  95

In [40]:
df[(df['도시'] == '서울') & (df['점수'] >= 90)]

    나이  도시  점수
철수  25  서울  90
민수  28  서울  95

In [41]:
df.loc["철수":"민수"]

    나이  도시  점수
철수  25  서울  90
영희  30  부산  85
민수  28  서울  95

In [42]:
df.iloc[0:2]

    나이  도시  점수
철수  25  서울  90
영희  30  부산  85

loc은 철수와 민수 index를 포함
iloc은 2를 포함 X

In [46]:
# 기존 방식
df[(df["나이"] >= 28 ) & (df["점수"] >= 90)]

    나이  도시  점수
민수  28  서울  95

In [47]:
# query 방식 - 같은 결과, 더 읽기 쉬움
df.query("나이 >= 28 and 점수 >= 90")

    나이  도시  점수
민수  28  서울  95

In [48]:
df.query("도시 == '서울'")

    나이  도시  점수
철수  25  서울  90
민수  28  서울  95

In [49]:
df.query("나이 >= 28 and 점수 >= 90")

    나이  도시  점수
민수  28  서울  95

In [50]:
df.query("점수 > 80 or 도시 == '대구'")

    나이  도시  점수
철수  25  서울  90
영희  30  부산  85
민수  28  서울  95
지수  35  대구  70

In [51]:
기준점수 = 90

df.query("점수 >= @기준점수")

    나이  도시  점수
철수  25  서울  90
민수  28  서울  95

In [52]:
df[df["도시"].isin(["서울", "대구"])]

    나이  도시  점수
철수  25  서울  90
민수  28  서울  95
지수  35  대구  70

In [54]:
df[(df["도시"] == "서울") | (df["도시"] == "대구")]

    나이  도시  점수
철수  25  서울  90
민수  28  서울  95
지수  35  대구  70

In [55]:
df[~df["도시"].isin(["서울"])]

    나이  도시  점수
영희  30  부산  85
지수  35  대구  70

In [56]:
df[df["나이"].between(28, 35)]

    나이  도시  점수
영희  30  부산  85
민수  28  서울  95
지수  35  대구  70

In [57]:
df[(df["나이"] >= 28) & (df["나이"] <= 35)]

    나이  도시  점수
영희  30  부산  85
민수  28  서울  95
지수  35  대구  70

In [58]:
# '도시'를 인덱스로 (기존 이름 인덱스는 사라짐)
df2 = df.set_index("도시")
print(df2)

df2.reset_index()

    나이  점수
도시
서울  25  90
부산  30  85
서울  28  95
대구  35  70

   도시  나이  점수
0  서울  25  90
1  부산  30  85
2  서울  28  95
3  대구  35  70

In [60]:
df.query("점수 > 85")

    나이  도시  점수
철수  25  서울  90
민수  28  서울  95

In [70]:
df[df['도시'].isin(['서울'])]

    나이  도시  점수
철수  25  서울  90
민수  28  서울  95

In [75]:
df[df['점수'].between(80, 90)]

    나이  도시  점수
철수  25  서울  90
영희  30  부산  85

In [78]:
최소나이 = 30

df.query("나이 >= @최소나이")

    나이  도시  점수
영희  30  부산  85
지수  35  대구  70

In [80]:
df.set_index("도시").loc["서울"]

    나이  점수
도시
서울  25  90
서울  28  95

In [82]:
df.loc[["철수", "민수"]]
df[df.index.isin(["철수", "민수"])]

    나이  도시  점수
철수  25  서울  90
민수  28  서울  95

In [83]:
df.set_index("도시").index.is_unique

False